const hashtags: Array<{ title: string; data: Array<string> }> = [
  {
    title: "General",
    data: [
      "# For You",
      "#OOTD",
      "#EverydayWear",
      "#WeekendVibes",
      "#WorkFromHome",
    ],
  },
  {
    title: "Seasons",
    data: [
      "#WinterCoats",
      "#SummerTees",
      "#FallLayers",
      "#SpringColors",
      "#SummerDresses",
      "#WinterBoots",
      "#FallJackets",
      "#SpringShoes",
    ],
  },
  {
    title: "Occasions",
    data: [
      "#BusinessCasual",
      "#WeekendStyle",
      "#DateOutfit",
      "#AthleticWear",
      "#WeddingAttire",
      "#VacationLooks",
      "#PartyOutfit",
      "#FormalWear",
    ],
  },
  {
    title: "Wears",
    data: [
      "#Denim",
      "#Polos",
      "#Hoodies",
      "#Sandals",
      "#Sneakers",
      "#Dresses",
      "#Jackets",
      "#Shirts",
      "#Tops",
      "#Pants",
      "#Skirts",
      "#Shorts",
      "#Suits",
      "#Swimwear",
      "#Underwear",
      "#Sleepwear",
    ],
  },
  {
    title: "Styles",
    data: [
      "#Minimalist",
      "#Urban",
      "#ComfortFirst",
      "#BusinessStyle",
      "#StreetStyle",
      "#Vintage",
      "#Boho",
      "#Glam",
      "#Preppy",
      "#Casual",
      "#Formal",
    ],
  },
  {
    title: "Brands",
    data: [
      "#Levis",
      "#Uniqlo",
      "#COS",
      "#Topshop",
      "#Zara",
      "#H&M",
      "#Aritzia",
      "#Everlane",
      "#FrankAndOak",
      "#ClubMonaco",
      "#BananaRepublic",
      "#Gap",
      "#OldNavy",
      "#JoeFresh",
      "#Roots",
      "#Simons",
      "#RW&Co",
      "#Nordstrom",
      "#NordstromRack",
      "#SaksOff5th",
      "#HoltRenfrew",
      "#HarryRosen",
      "#TheBay",
      "#Winners",
      "#Marshalls",
      "#TJMaxx",
      "#Amazon",
      "#Etsy",
      "#ASOS",
      "#Boohoo",
      "#PrettyLittleThing",
      "#Missguided",
      "#FashionNova",
      "#Shein",
      "#Romwe",
      "#YesStyle",
      "#Zulily",
      "#Walmart",
      "#Target",
      "#Costco",
      "#Superstore",
      "#Loblaws",
      "#Sobeys",
      "#Metro",
      "#WholeFoods",
      "#FreshCo",
      "#NoFrills",
      "#FoodBasics",
      "#Giant",
    ],
  },
  {
    title: "Inclusivity",
    data: ["#GenderNeutral", "#PlusSizeFashion", "#AllAgesStyle"],
  },
  {
    title: "Budget",
    data: ["#HighStreetFashion", "#BudgetFinds", "#LuxuryLooks"],
  },
  {
    title: "Trends",
    data: [
      "#NewArrivals",
      "#SeasonalFavorites",
      "#EcoFriendly",
      "#FashionForward",
    ],
  },
  {
    title: "Accessories",
    data: ["#Belts", "#Earrings", "#Backpacks", "#Scarves"],
  },
];

export default hashtags;
