"""empty message

Revision ID: 42383ac98073
Revises: 61300ea222f6
Create Date: 2023-10-11 15:36:32.064567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42383ac98073'
down_revision = '61300ea222f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outfit_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('x_pos', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('y_pos', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outfit_link', schema=None) as batch_op:
        batch_op.drop_column('y_pos')
        batch_op.drop_column('x_pos')

    # ### end Alembic commands ###
