"""empty message

Revision ID: 61300ea222f6
Revises: 
Create Date: 2023-10-11 15:36:05.425205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61300ea222f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outfit_link', schema=None) as batch_op:
        batch_op.drop_column('y_pos')
        batch_op.drop_column('x_pos')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outfit_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('x_pos', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('y_pos', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
