"""empty message

Revision ID: fd8c0ae9ee72
Revises: 42383ac98073
Create Date: 2023-10-11 15:41:35.286465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd8c0ae9ee72'
down_revision = '42383ac98073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outfit_link', schema=None) as batch_op:
        batch_op.drop_column('y_pos')
        batch_op.drop_column('x_pos')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outfit_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('x_pos', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('y_pos', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
